# nginx proxy address - http://172.17.0.1:8102

name: phpipam
x-logging: &default-logging
  driver: json-file
  options:
    max-size: "5m"
    max-file: "1"

services:
  phpipam:
    image: phpipam/phpipam-www:latest
    pull_policy: always
    container_name: phpipam-app
    restart: always
    logging: *default-logging
    networks:
      - phpipam
      - proxy
      - cloudflare
    ports:
      - "172.17.0.1:8102:80"
    environment:
      TZ: ${TZ:-America/New_York}
      IPAM_DATABASE_HOST: phpipam-db
      IPAM_DATABASE_NAME: ${DB_CREATE_DATABASE_NAME:-phpipam}
      IPAM_DATABASE_USER: ${DB_USER_NAME:-phpipam}
      IPAM_DATABASE_PASS: ${DB_USER_PASS:-changeme_db_password}
      IPAM_DATABASE_WEBHOST: "%"
      CONTAINER_NAME: phpipam-app
      HOSTNAME: ${BASE_HOST_NAME:-$HOSTNAME}
    depends_on:
      - phpipam-db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - 'traefik.enable=true'
      - 'cloudflare.enable=true'
      - 'traefik.docker.network=proxy'
      - 'cloudflare.service=http://phpipam-app:80'
      - 'cloudflare.hostname=phpipam.${CLOUDFLARE_ZONE_NAME:-}'
      - 'traefik.http.routers.phpipam-app.entrypoints=http'
      - 'traefik.http.routers.phpipam-app-secure.tls=true'
      - 'traefik.http.routers.phpipam-app.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.middlewares.phpipam-app-https-redirect.redirectscheme.scheme=https'
      - 'traefik.http.routers.phpipam-app.middlewares=phpipam-app-https-redirect'
      - 'traefik.http.routers.phpipam-app-secure.entrypoints=https'
      - 'traefik.http.routers.phpipam-app-secure.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.routers.phpipam-app-secure.tls.certresolver=cloudflare'
      - 'traefik.http.routers.phpipam-app-secure.service=phpipam-app'
      - 'traefik.http.services.phpipam-app.loadbalancer.server.port=80'

  phpipam-db:
    image: mariadb:latest
    pull_policy: always
    container_name: phpipam-db
    restart: always
    logging: *default-logging
    networks:
      - phpipam
    environment:
      TZ: ${TZ:-America/New_York}
      MARIADB_DATABASE: ${DB_CREATE_DATABASE_NAME:-phpipam}
      MARIADB_USER: ${DB_USER_NAME:-phpipam}
      MARIADB_PASSWORD: ${DB_USER_PASS:-changeme_db_password}
      MARIADB_ROOT_PASSWORD: ${DB_ADMIN_PASS:-changeme_admin_password}
      CONTAINER_NAME: phpipam-db
    volumes:
      - ./volumes/data/db/mariadb/phpipam:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  phpipam:
    external: false
  proxy:
    external: true
  cloudflare:
    external: true
